### PR TITLE
Fix for Nim 1.6.6

### PR DESCRIPTION
**Pull request by mildred**
pegs matches are not longer working well and string conversion from Sha1Digest leads to debug representation instead of keeping the underlying bytes. Keep pegs for validating the format but hand parse the messages. See probable issue: https://github.com/nim-lang/Nim/issues/19104
    
Added server and client/server tests.
    
Added constant time check for server implementation.

### CODE REVIEW

**Comment by mildred** [comment]
See the pegs matches issue in https://github.com/nim-lang/Nim/issues/19104#issuecomment-1192973637

Thank you for the yesterday PR quickly merged :)

**Comment by mildred** [comment]
Good news, with this my [NimNews](https://github.com/mildred/nimnews) client is connecting to my server :)

**Comment by Neustradamus** [comment]
@ba0f3: What do you think about this PR?

**Comment by ba0f3** [comment]
Im sorry, Im on vacation. I will check it soon

**Pull request merged**
